In [1]:
# Data Preprocessing Tools

## Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
## Importing the dataset

dataset=pd.read_csv('Data.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [6]:
print(x)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [7]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [8]:
## Encoding categorical data

from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])

print(x)



[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [9]:
### Encoding the Independent Variable

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

print(x)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [10]:

### Encoding the Dependent Variable

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

print(y)



[0 1 0 0 1 1 0 1 0 1]


In [11]:
## Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)

## Feature Scaling

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:]=sc.transform(x_test[:,3:])

print(x_train)



[[0.0 1.0 0.0 -1.2597958529291027 -0.8388998277785314]
 [0.0 1.0 0.0 0.0701939038288944 -0.026540159613350534]
 [1.0 0.0 0.0 1.134185709235292 1.238156141961987]
 [0.0 0.0 1.0 -1.6587927799565019 -1.337393260516256]
 [1.0 0.0 0.0 0.6021898065320932 0.656580470434642]
 [0.0 1.0 0.0 1.4001836605868916 1.5704850971204702]
 [0.0 0.0 1.0 -0.0923603997748607 -1.0050643053577728]
 [0.0 0.0 1.0 -0.19580404752270503 -0.2573241562511862]]


In [12]:
print(x_test)

[[1.0 0.0 0.0 -0.32880302319850474 0.24116927648653827]
 [1.0 0.0 0.0 -0.5948009745501042 -0.5065708726200484]]
